package baseDatos;

public class querysBaseDatos {
	/*SE CREO LA BASE DE DATOS
	CREATE DATABASE Proyecto_Final_Web;
	USE Proyecto_Final_Web;



	-- MySQL Script generated by MySQL Workbench
	-- Sat Jul  9 15:32:09 2022
	-- Model: New Model    Version: 1.0
	-- MySQL Workbench Forward Engineering

	SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

	-- -----------------------------------------------------
	-- Schema mydb
	-- -----------------------------------------------------

	-- -----------------------------------------------------
	-- Schema mydb
	-- -----------------------------------------------------
	CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
	USE `mydb` ;

	-- -----------------------------------------------------
	-- Table `mydb`.`Usuario`
	 SE CREO LA TABLA USUARIOS
	-- -----------------------------------------------------
	CREATE TABLE IF NOT EXISTS `Proyecto_Final_Web`.`Usuario` (
	  `id_Usuario` INT NOT NULL,
	  `nombre_completo` VARCHAR(40) NOT NULL,
	  `email` VARCHAR(255) NOT NULL,
	  `contraseña` VARCHAR(32) NOT NULL,
	  PRIMARY KEY (`id_Usuario`))
	ENGINE = InnoDB;



	-- -----------------------------------------------------
	-- Table `mydb`.`Categoria_Producto`/* SE CREO LA TABLA CATEGORIA_PRODUCTOS
	-- -----------------------------------------------------
	CREATE TABLE IF NOT EXISTS `Proyecto_Final_Web`.`Categoria_Producto` (
	  `id_Categoria` INT NOT NULL ,
	  `nombre_Categoria` VARCHAR(40) NOT NULL,
	  PRIMARY KEY (`id_Categoria`))
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `mydb`.`Producto` /* SE CREO LA TABLA PRODUCTO
	-- -----------------------------------------------------
	CREATE TABLE IF NOT EXISTS `Proyecto_Final_Web`.`Producto` (
	  `id_Producto` INT NOT NULL AUTO_INCREMENT,
	  `descripcion` VARCHAR(255) NOT NULL,
	  `imagen_Producto` VARCHAR(255) NULL,
	  `precio_Producto` VARCHAR(32) NOT NULL,
	  `Categoria_Producto_id_Categoria` INT NOT NULL,
	  PRIMARY KEY (`id_Producto`),
	  CONSTRAINT `fk_Producto_Categoria_Producto`
	    FOREIGN KEY (`Categoria_Producto_id_Categoria`)
	    REFERENCES `Proyecto_Final_Web`.`Categoria_Producto` (`id_Categoria`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION)
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `mydb`.`detalle_Orden`/* SE CREO LA TABLA DETALLE_ORDEN
	-- -----------------------------------------------------
	CREATE TABLE IF NOT EXISTS `Proyecto_Final_Web`.`detalle_Orden` (
	  `id_Detalle_Orden` INT NOT NULL AUTO_INCREMENT,
	  `Producto_id_Producto` INT NOT NULL,
	  `Usuario_id_Usuario` INT NOT NULL,
	  PRIMARY KEY ( `id_Detalle_Orden`),
	  CONSTRAINT `fk_Producto_has_Usuario_Producto1`
	    FOREIGN KEY (`Producto_id_Producto`)
	    REFERENCES `Proyecto_Final_Web`.`Producto` (`id_Producto`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	  CONSTRAINT `fk_Producto_has_Usuario_Usuario1`
	    FOREIGN KEY (`Usuario_id_Usuario`)
	    REFERENCES `Proyecto_Final_Web`.`Usuario` (`id_Usuario`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION)
	ENGINE = InnoDB;


	SET SQL_MODE=@OLD_SQL_MODE;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
	SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
*/
}
